export interface ArabicWord {
  arabic: string;
  translit: string;
  english: string;
  category: string;
}

export function formatArabic(text: string, showDiacritics: boolean): string {
  if (showDiacritics) return text;
  // Remove Arabic diacritical marks (Tashkeel/Harakat)
  return text.replace(/[\u064B-\u065F\u0670]/g, '');
}

export const ARABIC_VOCABULARY: ArabicWord[] = [
  // Greetings (10)
  { arabic: "مَرْحَبًا",        translit: "marhaban",        english: "hello",              category: "greetings" },
  { arabic: "السَّلَامُ عَلَيْكُمْ", translit: "assalamu alaykum",english: "peace be upon you",  category: "greetings" },
  { arabic: "شُكْرًا",         translit: "shukran",         english: "thank you",           category: "greetings" },
  { arabic: "عَفْوًا",         translit: "afwan",           english: "you're welcome",      category: "greetings" },
  { arabic: "مِنْ فَضْلِكَ",      translit: "min fadlak",      english: "please",              category: "greetings" },
  { arabic: "نَعَمْ",          translit: "na'am",           english: "yes",                 category: "greetings" },
  { arabic: "لَا",           translit: "la",              english: "no",                  category: "greetings" },
  { arabic: "مَعَ السَّلَامَةِ",   translit: "ma'a ssalama",   english: "goodbye",             category: "greetings" },
  { arabic: "صَبَاحُ الْخَيْرِ",   translit: "sabah al-khayr", english: "good morning",        category: "greetings" },
  { arabic: "مَسَاءُ الْخَيْرِ",   translit: "masa al-khayr",  english: "good evening",        category: "greetings" },
  // Numbers (15)
  { arabic: "وَاحِد",  translit: "wahid",    english: "one",      category: "numbers" },
  { arabic: "اِثْنَان", translit: "ithnan",   english: "two",      category: "numbers" },
  { arabic: "ثَلَاثَة", translit: "thalatha", english: "three",    category: "numbers" },
  { arabic: "أَرْبَعَة", translit: "arba'a",   english: "four",     category: "numbers" },
  { arabic: "خَمْسَة",  translit: "khamsa",   english: "five",     category: "numbers" },
  { arabic: "سِتَّة",   translit: "sitta",    english: "six",      category: "numbers" },
  { arabic: "سَبْعَة",  translit: "sab'a",    english: "seven",    category: "numbers" },
  { arabic: "ثَمَانِيَة",translit: "thamaniya",english: "eight",    category: "numbers" },
  { arabic: "تِسْعَة",  translit: "tis'a",    english: "nine",     category: "numbers" },
  { arabic: " عَشَرَة",  translit: "ashara",   english: "ten",      category: "numbers" },
  { arabic: "عِشْرُون", translit: "ishrun",   english: "twenty",   category: "numbers" },
  { arabic: "ثَلَاثُون",translit: "thalathun",english: "thirty",   category: "numbers" },
  { arabic: "مِئَة",   translit: "mi'a",     english: "hundred",  category: "numbers" },
  { arabic: "أَلْف",   translit: "alf",      english: "thousand", category: "numbers" },
  { arabic: "صِفْر",   translit: "sifr",     english: "zero",     category: "numbers" },
  // Colors (10)
  { arabic: "أَحْمَر",    translit: "ahmar",     english: "red",    category: "colors" },
  { arabic: "أَزْرَق",    translit: "azraq",     english: "blue",   category: "colors" },
  { arabic: "أَخْضَر",    translit: "akhdar",    english: "green",  category: "colors" },
  { arabic: "أَصْفَر",    translit: "asfar",     english: "yellow", category: "colors" },
  { arabic: "أَبْيَض",    translit: "abyad",     english: "white",  category: "colors" },
  { arabic: "أَسْوَد",    translit: "aswad",     english: "black",  category: "colors" },
  { arabic: "بَنَفْسَجِيّ",  translit: "banafsaji", english: "purple", category: "colors" },
  { arabic: "بُرْتُقَالِيّ", translit: "burtuqali", english: "orange", category: "colors" },
  { arabic: "وَرْدِيّ",    translit: "wardi",     english: "pink",   category: "colors" },
  { arabic: "بُنِّيّ",     translit: "bunni",     english: "brown",  category: "colors" },
  // Family (10)
  { arabic: "أَب",  translit: "ab",   english: "father",           category: "family" },
  { arabic: "أُمّ",  translit: "umm",  english: "mother",           category: "family" },
  { arabic: "أَخ",  translit: "akh",  english: "brother",          category: "family" },
  { arabic: "أُخْت", translit: "ukht", english: "sister",           category: "family" },
  { arabic: "اِبْن", translit: "ibn",  english: "son",              category: "family" },
  { arabic: "بِنْت", translit: "bint", english: "daughter",         category: "family" },
  { arabic: "جَدّ",  translit: "jadd", english: "grandfather",      category: "family" },
  { arabic: "جَدَّة", translit: "jadda",english: "grandmother",      category: "family" },
  { arabic: "عَمّ",  translit: "amm",  english: "paternal uncle",   category: "family" },
  { arabic: "خَال", translit: "khal", english: "maternal uncle",   category: "family" },
  // Body (10)
  { arabic: "رَأْس", translit: "ra's",  english: "head",    category: "body" },
  { arabic: "عَيْن", translit: "ayn",   english: "eye",     category: "body" },
  { arabic: "أُذُن", translit: "udhn",  english: "ear",     category: "body" },
  { arabic: "أَنْف", translit: "anf",   english: "nose",    category: "body" },
  { arabic: "فَم",  translit: "famm",  english: "mouth",   category: "body" },
  { arabic: "يَد",  translit: "yad",   english: "hand",    category: "body" },
  { arabic: "رِجْل", translit: "rijl",  english: "leg",     category: "body" },
  { arabic: "قَلْب", translit: "qalb",  english: "heart",   category: "body" },
  { arabic: "ظَهْر", translit: "dahr",  english: "back",    category: "body" },
  { arabic: "بَطْن", translit: "batn",  english: "stomach", category: "body" },
  // Food (15)
  { arabic: "مَاء",   translit: "ma'",    english: "water",   category: "food" },
  { arabic: "خُبْز",   translit: "khubz",  english: "bread",   category: "food" },
  { arabic: "أَرُزّ",   translit: "aruzz",  english: "rice",    category: "food" },
  { arabic: "لَحْم",   translit: "lahm",   english: "meat",    category: "food" },
  { arabic: "سَمَك",   translit: "samak",  english: "fish",    category: "food" },
  { arabic: "دَجَاج",  translit: "dajaj",  english: "chicken", category: "food" },
  { arabic: "تُفَّاح",  translit: "tuffah", english: "apple",   category: "food" },
  { arabic: "مَوْز",   translit: "mawz",   english: "banana",  category: "food" },
  { arabic: "حَلِيب",  translit: "halib",  english: "milk",    category: "food" },
  { arabic: "قَهْوَة",  translit: "qahwa",  english: "coffee",  category: "food" },
  { arabic: "شَاي",   translit: "shay",   english: "tea",     category: "food" },
  { arabic: "عَصِير",  translit: "asir",   english: "juice",   category: "food" },
  { arabic: "بَيْضَة",  translit: "bayda",  english: "egg",     category: "food" },
  { arabic: "جُبْن",   translit: "jubn",   english: "cheese",  category: "food" },
  { arabic: "سُكَّر",   translit: "sukkar", english: "sugar",   category: "food" },
  // Time (10)
  { arabic: "يَوْم",   translit: "yawm",    english: "day",       category: "time" },
  { arabic: "أُسْبُوع", translit: "usbu'",   english: "week",      category: "time" },
  { arabic: "شَهْر",   translit: "shahr",   english: "month",     category: "time" },
  { arabic: "سَنَة",   translit: "sana",    english: "year",      category: "time" },
  { arabic: "سَاعَة",  translit: "sa'a",    english: "hour",      category: "time" },
  { arabic: "اَلْآن",  translit: "al-an",   english: "now",       category: "time" },
  { arabic: "اَلْيَوْم", translit: "al-yawm", english: "today",     category: "time" },
  { arabic: "غَدًا",   translit: "ghadan",  english: "tomorrow",  category: "time" },
  { arabic: "أَمْسِ",   translit: "ams",     english: "yesterday", category: "time" },
  { arabic: "لَيْل",   translit: "layl",    english: "night",     category: "time" },
  // Nature (10)
  { arabic: "شَمْس",  translit: "shams",  english: "sun",      category: "nature" },
  { arabic: "قَمَر",  translit: "qamar",  english: "moon",     category: "nature" },
  { arabic: "نَجْم",  translit: "najm",   english: "star",     category: "nature" },
  { arabic: "مَطَر",  translit: "matar",  english: "rain",     category: "nature" },
  { arabic: "ثَلْج",  translit: "thalj",  english: "snow",     category: "nature" },
  { arabic: "رِيح",  translit: "rih",    english: "wind",     category: "nature" },
  { arabic: "بَحْر",  translit: "bahr",   english: "sea",      category: "nature" },
  { arabic: "جَبَل",  translit: "jabal",  english: "mountain", category: "nature" },
  { arabic: "نَهْر",  translit: "nahr",   english: "river",    category: "nature" },
  { arabic: "شَجَرَة", translit: "shajara",english: "tree",     category: "nature" },
  // Places (15)
  { arabic: "بَيْت",     translit: "bayt",      english: "house",    category: "places" },
  { arabic: "غُرْفَة",    translit: "ghurfa",    english: "room",     category: "places" },
  { arabic: "مَطْبَخ",    translit: "matbakh",   english: "kitchen",  category: "places" },
  { arabic: "حَمَّام",    translit: "hammam",    english: "bathroom", category: "places" },
  { arabic: "بَاب",     translit: "bab",       english: "door",     category: "places" },
  { arabic: "نَافِذَة",   translit: "nafidha",   english: "window",   category: "places" },
  { arabic: "مَدْرَسَة",   translit: "madrasa",   english: "school",   category: "places" },
  { arabic: "مُسْتَشْفَى",  translit: "mustashfa", english: "hospital", category: "places" },
  { arabic: "سُوق",     translit: "suq",       english: "market",   category: "places" },
  { arabic: "مَسْجِد",    translit: "masjid",    english: "mosque",   category: "places" },
  { arabic: "شَارِع",    translit: "shari'",    english: "street",   category: "places" },
  { arabic: "مَدِينَة",   translit: "madina",    english: "city",     category: "places" },
  { arabic: "قَرْيَة",    translit: "qarya",     english: "village",  category: "places" },
  { arabic: "فُنْدُق",    translit: "funduq",    english: "hotel",    category: "places" },
  { arabic: "مَطَار",    translit: "matar2",    english: "airport",  category: "places" },
  // Verbs (20)
  { arabic: "ذَهَبَ",  translit: "dhahaba",  english: "to go",          category: "verbs" },
  { arabic: "جَاءَ",  translit: "ja'a",     english: "to come",        category: "verbs" },
  { arabic: "أَكَلَ",  translit: "akala",    english: "to eat",         category: "verbs" },
  { arabic: "شَرِبَ",  translit: "shariba",  english: "to drink",       category: "verbs" },
  { arabic: "نَامَ",  translit: "nama",     english: "to sleep",       category: "verbs" },
  { arabic: "قَرَأَ",  translit: "qara'a",   english: "to read",        category: "verbs" },
  { arabic: "كَتَبَ",  translit: "kataba",   english: "to write",       category: "verbs" },
  { arabic: "تَكَلَّمَ", translit: "takallama",english: "to speak",       category: "verbs" },
  { arabic: "سَمِعَ",  translit: "sami'a",   english: "to hear",        category: "verbs" },
  { arabic: "رَأَى",  translit: "ra'a",     english: "to see",         category: "verbs" },
  { arabic: "عَرَفَ",  translit: "arafa",    english: "to know",        category: "verbs" },
  { arabic: "أَحَبَّ",  translit: "ahabba",   english: "to love",        category: "verbs" },
  { arabic: "فَهِمَ",  translit: "fahima",   english: "to understand",  category: "verbs" },
  { arabic: "فَعَلَ",  translit: "fa'ala",   english: "to do",          category: "verbs" },
  { arabic: "أَخَذَ",  translit: "akhadha",  english: "to take",        category: "verbs" },
  { arabic: "أَعْطَى", translit: "a'ta",     english: "to give",        category: "verbs" },
  { arabic: "فَتَحَ",  translit: "fataha",   english: "to open",        category: "verbs" },
  { arabic: "أَغْلَقَ", translit: "aghlaqa",  english: "to close",       category: "verbs" },
  { arabic: "جَلَسَ",  translit: "jalasa",   english: "to sit",         category: "verbs" },
  { arabic: "وَقَفَ",  translit: "waqafa",   english: "to stand",       category: "verbs" },
  // Adjectives (15)
  { arabic: "كَبِير",  translit: "kabir",  english: "big",       category: "adjectives" },
  { arabic: "صَغِير",  translit: "saghir", english: "small",     category: "adjectives" },
  { arabic: "جَدِيد",  translit: "jadid",  english: "new",       category: "adjectives" },
  { arabic: "قَدِيم",  translit: "qadim",  english: "old",       category: "adjectives" },
  { arabic: "جَمِيل",  translit: "jamil",  english: "beautiful", category: "adjectives" },
  { arabic: "سَرِيع",  translit: "sari'",  english: "fast",      category: "adjectives" },
  { arabic: "بَطِيء",  translit: "bati'",  english: "slow",      category: "adjectives" },
  { arabic: "قَرِيب",  translit: "qarib",  english: "near",      category: "adjectives" },
  { arabic: "بَعِيد",  translit: "ba'id",  english: "far",       category: "adjectives" },
  { arabic: "غَالِي",  translit: "ghali",  english: "expensive", category: "adjectives" },
  { arabic: "رَخِيص",  translit: "rakhis", english: "cheap",     category: "adjectives" },
  { arabic: "ذَكِيّ",   translit: "dhaki",  english: "smart",     category: "adjectives" },
  { arabic: "طَوِيل",  translit: "tawil",  english: "tall",      category: "adjectives" },
  { arabic: "قَصِير",  translit: "qasir",  english: "short",     category: "adjectives" },
  { arabic: "ثَقِيل",  translit: "thaqil", english: "heavy",     category: "adjectives" },
  // Questions & Pronouns (10)
  { arabic: "مَنْ",    translit: "man",    english: "who",           category: "questions" },
  { arabic: "مَا",    translit: "ma",     english: "what",          category: "questions" },
  { arabic: "أَيْنَ",   translit: "ayna",   english: "where",         category: "questions" },
  { arabic: "مَتَى",   translit: "mata",   english: "when",          category: "questions" },
  { arabic: "كَيْفَ",   translit: "kayfa",  english: "how",           category: "questions" },
  { arabic: "لِمَاذَا", translit: "limadha",english: "why",           category: "questions" },
  { arabic: "كَمْ",    translit: "kam",    english: "how many",      category: "questions" },
  { arabic: "أَنَا",   translit: "ana",    english: "I / me",        category: "questions" },
  { arabic: "أَنْتَ",   translit: "anta",   english: "you",           category: "questions" },
  { arabic: "هُوَ",    translit: "huwa",   english: "he",            category: "questions" },
  // Transport (10)
  { arabic: "سَيَّارَة", translit: "sayyara",english: "car",      category: "transport" },
  { arabic: "حَافِلَة", translit: "hafila", english: "bus",      category: "transport" },
  { arabic: "قِطَار",  translit: "qitar",  english: "train",    category: "transport" },
  { arabic: "طَائِرَة", translit: "ta'ira", english: "airplane", category: "transport" },
  { arabic: "سَفِينَة", translit: "safina", english: "ship",     category: "transport" },
  { arabic: "دَرَّاجَة", translit: "darraja",english: "bicycle",  category: "transport" },
  { arabic: "تَأْكْسِي", translit: "taksi",  english: "taxi",     category: "transport" },
  { arabic: "طَرِيق",  translit: "tariq",  english: "road",     category: "transport" },
  { arabic: "جِسْر",   translit: "jisr",   english: "bridge",   category: "transport" },
  { arabic: "مَحَطَّة",  translit: "mahatta",english: "station",  category: "transport" },
  // Education (10)
  { arabic: "كِتَاب",  translit: "kitab",    english: "book",      category: "education" },
  { arabic: "قَلَم",   translit: "qalam",    english: "pen",       category: "education" },
  { arabic: "دَرْس",   translit: "dars",     english: "lesson",    category: "education" },
  { arabic: "اِمْتِحَان",translit: "imtihan",  english: "exam",      category: "education" },
  { arabic: "مُعَلِّم",  translit: "mu'allim", english: "teacher",   category: "education" },
  { arabic: "طَالِب",  translit: "talib",    english: "student",   category: "education" },
  { arabic: "مَكْتَب",  translit: "maktab",   english: "office",    category: "education" },
  { arabic: "عَمَل",   translit: "amal",     english: "work",      category: "education" },
  { arabic: "وَظِيفَة", translit: "wazifa",   english: "job",       category: "education" },
  { arabic: "مُهَنْدِس", translit: "muhandis", english: "engineer",  category: "education" },
  // Health (10)
  { arabic: "صِحَّة",  translit: "sihha",  english: "health",    category: "health" },
  { arabic: "مَرِيض", translit: "marid",  english: "sick",      category: "health" },
  { arabic: "دَوَاء", translit: "dawa'",  english: "medicine",  category: "health" },
  { arabic: "طَبِيب", translit: "tabib",  english: "doctor",    category: "health" },
  { arabic: "أَلَم",  translit: "alam",   english: "pain",      category: "health" },
  { arabic: "حُمَّى",  translit: "humma",  english: "fever",     category: "health" },
  { arabic: "جُرْح",  translit: "jurh",   english: "wound",     category: "health" },
  { arabic: "صُدَاع", translit: "suda'",  english: "headache",  category: "health" },
  { arabic: "نَوْم",  translit: "nawm",   english: "sleep",     category: "health" },
  { arabic: "رَاحَة", translit: "raha",   english: "rest",      category: "health" },
  // Technology (10)
  { arabic: "هَاتِف",   translit: "hatif",    english: "phone",     category: "technology" },
  { arabic: "حَاسُوب",  translit: "hasub",    english: "computer",  category: "technology" },
  { arabic: "إِنْتَرْنِت", translit: "internet", english: "internet",  category: "technology" },
  { arabic: "بَرْنَامَج", translit: "barnmaj",  english: "software",  category: "technology" },
  { arabic: "شَاشَة",   translit: "shasha",   english: "screen",    category: "technology" },
  { arabic: "كَامِيرَا", translit: "kamira",   english: "camera",    category: "technology" },
  { arabic: "كَهْرَبَاء", translit: "kahrabaa", english: "electricity",category: "technology" },
  { arabic: "بَطَّارِيَّة", translit: "battariya",english: "battery",   category: "technology" },
  { arabic: "شَبَكَة",   translit: "shabaka",  english: "network",   category: "technology" },
  { arabic: "رِسَالَة",  translit: "risala",   english: "message",   category: "technology" },
  // Animals (10)
  { arabic: "كَلْب",  translit: "kalb",    english: "dog",      category: "animals" },
  { arabic: "قِطَّة",  translit: "qitta",   english: "cat",      category: "animals" },
  { arabic: "حِصَان", translit: "hisan",   english: "horse",    category: "animals" },
  { arabic: "أَسَد",  translit: "asad",    english: "lion",     category: "animals" },
  { arabic: "فِيل",  translit: "fil",     english: "elephant", category: "animals" },
  { arabic: "طَيْر",  translit: "tayr",    english: "bird",     category: "animals" },
  { arabic: "جَمَل",  translit: "jamal",   english: "camel",    category: "animals" },
  { arabic: "ثَعْلَب", translit: "tha'lab", english: "fox",      category: "animals" },
  { arabic: "أَرْنَب", translit: "arnab",   english: "rabbit",   category: "animals" },
  { arabic: "سَمَكَة", translit: "samaka",  english: "fish",     category: "animals" },
];

export const CATEGORIES = [...new Set(ARABIC_VOCABULARY.map(w => w.category))];
